# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Category.create([
	{title:"Graphics & Design", subtitle:"Cartoons & Caricatures"},
	{title:"Graphics & Design", subtitle:"Logo Design"},
	{title:"Graphics & Design", subtitle:"Illustration"},
	{title:"Graphics & Design", subtitle:"Ebook Covers & Packages"},
	{title:"Graphics & Design", subtitle:"Web Design & UI"},
	{title:"Graphics & Design", subtitle:"Photography & Photoshopping"},
	{title:"Graphics & Design", subtitle:"Presentation Design"},
	{title:"Graphics & Design", subtitle:"Flyers & Brochures "},
	{title:"Graphics & Design", subtitle:"Business Cards"},
	{title:"Graphics & Design", subtitle:"Banners & Headers"},
	{title:"Graphics & Design", subtitle:"Architecture"},
	{title:"Graphics & Design", subtitle:"Landing Pages"},
	{title:"Graphics & Design", subtitle:"Other"},

	{title:"Online Marketing", subtitle:"Web Analytics"},
	{title:"Online Marketing", subtitle:"Article & PR Submission"},
	{title:"Online Marketing", subtitle:"Blog Mentions"},
	{title:"Online Marketing", subtitle:"Domain Research"},
	{title:"Online Marketing", subtitle:"Fan Pages"},
	{title:"Online Marketing", subtitle:"Keywords Research"},
	{title:"Online Marketing", subtitle:"SEO"},
	{title:"Online Marketing", subtitle:"Bookmarking & Links"},
	{title:"Online Marketing", subtitle:"Social Marketing"},
	{title:"Online Marketing", subtitle:"Get Traffic"},
	{title:"Online Marketing", subtitle:"Video Marketing"},
	{title:"Online Marketing", subtitle:"Other"},

	{title:"Writing & Translation", subtitle:"Copywriting"},
	{title:"Writing & Translation", subtitle:"SEO Keyword Optimization"},
	{title:"Writing & Translation", subtitle:"Creative Writing & Scripting"},
	{title:"Writing & Translation", subtitle:"Translation"},
	{title:"Writing & Translation", subtitle:"Transcripts"},
	{title:"Writing & Translation", subtitle:"Website Content"},
	{title:"Writing & Translation", subtitle:"Reviews"},
	{title:"Writing & Translation", subtitle:"Resumes & Cover Letters"},
	{title:"Writing & Translation", subtitle:"Speech Writing"},
	{title:"Writing & Translation", subtitle:"Proofreading & Editing"},
	{title:"Writing & Translation", subtitle:"Press Releases"},
	{title:"Writing & Translation", subtitle:"Other"},

	{title:"Video & Animation", subtitle:"Commercials"},
	{title:"Video & Animation", subtitle:"Editing & Post Production"},
	{title:"Video & Animation", subtitle:"Animation & 3D"},
	{title:"Video & Animation", subtitle:"Testimonials & Reviews by Actors"},
	{title:"Video & Animation", subtitle:"Puppets"},
	{title:"Video & Animation", subtitle:"Stop Motion"},
	{title:"Video & Animation", subtitle:"Intros"},
	{title:"Video & Animation", subtitle:"Other"},

	{title:"Music & Audio", subtitle:"Audio Editing & Mastering"},
	{title:"Music & Audio", subtitle:"Jingles"},
	{title:"Music & Audio", subtitle:"Songwriting"},
	{title:"Music & Audio", subtitle:"Music Lessons"},
	{title:"Music & Audio", subtitle:"Rap Music"},
	{title:"Music & Audio", subtitle:"Hip-Hop Music"},
	{title:"Music & Audio", subtitle:"Narration & Voice-Over"},
	{title:"Music & Audio", subtitle:"Sound Effects & Loops"},
	{title:"Music & Audio", subtitle:"Custom Ringtones"},
	{title:"Music & Audio", subtitle:"Voicemail Greetings"},
	{title:"Music & Audio", subtitle:"Custom Songs"},
	{title:"Music & Audio", subtitle:"Other"},

	{title:"Programming & Tech", subtitle:".Net"},
	{title:"Programming & Tech", subtitle:"C++"},
	{title:"Programming & Tech", subtitle:"CSS & HTML"},
	{title:"Programming & Tech", subtitle:"Joomla & Drupal"},
	{title:"Programming & Tech", subtitle:"Databases"},
	{title:"Programming & Tech", subtitle:"Java"},
	{title:"Programming & Tech", subtitle:"JavaScript"},
	{title:"Programming & Tech", subtitle:"PSD to HTML"},
	{title:"Programming & Tech", subtitle:"WordPress"},
	{title:"Programming & Tech", subtitle:"Flash"},
	{title:"Programming & Tech", subtitle:"iOS, Android & Mobile"},
	{title:"Programming & Tech", subtitle:"PHP"},
	{title:"Programming & Tech", subtitle:"QA & Software Testing"},
	{title:"Programming & Tech", subtitle:"Technology"},
	{title:"Programming & Tech", subtitle:"Other"},

	{title:"Gifts", subtitle:"Greeting Cards"},
	{title:"Gifts", subtitle:"Video Greetings"},
	{title:"Gifts", subtitle:"Unusual Gifts"},
	{title:"Gifts", subtitle:"Arts & Crafts"},
	{title:"Gifts", subtitle:"Handmade Jewelry"},
	{title:"Gifts", subtitle:"Gifts for Geeks"},
	{title:"Gifts", subtitle:"Postcards From..."},
	{title:"Gifts", subtitle:"Recycled Crafts"},
	{title:"Gifts", subtitle:"Other"},

	])