# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Category.create([
	{title:"Graphics & Design", subtitle:"Cartoons & Caricatures", category_url:"graphics-design", subcategory_url: "cartoons-caricatures"},
	{title:"Graphics & Design", subtitle:"Logo Design", category_url:"graphics-design", subcategory_url: "logo-design"},
	{title:"Graphics & Design", subtitle:"Illustration", category_url:"graphics-design", subcategory_url: "illustration"},
	{title:"Graphics & Design", subtitle:"Ebook Covers & Packages", category_url:"graphics-design", subcategory_url: "ebook-covers-packages"},
	{title:"Graphics & Design", subtitle:"Web Design & UI", category_url:"graphics-design", subcategory_url: "web-design-ui"},
	{title:"Graphics & Design", subtitle:"Photography & Photoshopping", category_url:"graphics-design", subcategory_url: "photography-photoshopping"},
	{title:"Graphics & Design", subtitle:"Presentation Design", category_url:"graphics-design", subcategory_url: "presentation-design"},
	{title:"Graphics & Design", subtitle:"Flyers & Brochures ", category_url:"graphics-design", subcategory_url: "flyers-brochures"},
	{title:"Graphics & Design", subtitle:"Business Cards", category_url:"graphics-design", subcategory_url: "business-cards"},
	{title:"Graphics & Design", subtitle:"Banners & Headers", category_url:"graphics-design", subcategory_url: "banners-headers"},
	{title:"Graphics & Design", subtitle:"Architecture", category_url:"graphics-design", subcategory_url: "architecture"},
	{title:"Graphics & Design", subtitle:"Landing Pages", category_url:"graphics-design", subcategory_url: "landing-pages"},
	{title:"Graphics & Design", subtitle:"Other", category_url:"graphics-design", subcategory_url: "other"},

	{title:"Online Marketing", subtitle:"Web Analytics", category_url:"online-marketing", subcategory_url: "web-analytics"},
	{title:"Online Marketing", subtitle:"Article & PR Submission", category_url:"online-marketing", subcategory_url: "article-pr-submitssion"},
	{title:"Online Marketing", subtitle:"Blog Mentions", category_url:"online-marketing", subcategory_url: "blog-mentions"},
	{title:"Online Marketing", subtitle:"Domain Research", category_url:"online-marketing", subcategory_url: "domain-research"},
	{title:"Online Marketing", subtitle:"Fan Pages", category_url:"online-marketing", subcategory_url: "fan-pages"},
	{title:"Online Marketing", subtitle:"Keywords Research", category_url:"online-marketing", subcategory_url: "keyword-research"},
	{title:"Online Marketing", subtitle:"SEO", category_url:"online-marketing", subcategory_url: "seo"},
	{title:"Online Marketing", subtitle:"Bookmarking & Links", category_url:"online-marketing", subcategory_url: "bookmarking-links"},
	{title:"Online Marketing", subtitle:"Social Marketing", category_url:"online-marketing", subcategory_url: "social-marketing"},
	{title:"Online Marketing", subtitle:"Get Traffic", category_url:"online-marketing", subcategory_url: "get-traffic"},
	{title:"Online Marketing", subtitle:"Video Marketing", category_url:"online-marketing", subcategory_url: "video-marketing"},
	{title:"Online Marketing", subtitle:"Other", category_url:"online-marketing", subcategory_url: "other"},

	{title:"Writing & Translation", subtitle:"Copywriting", category_url:"writing-translation", subcategory_url: "copywriting"},
	{title:"Writing & Translation", subtitle:"SEO Keyword Optimization", category_url:"writing-translation", subcategory_url: "seo-keyword-optimization"},
	{title:"Writing & Translation", subtitle:"Creative Writing & Scripting", category_url:"writing-translation", subcategory_url: "creattive-writing-scripting"},
	{title:"Writing & Translation", subtitle:"Translation", category_url:"writing-translation", subcategory_url: "translation"},
	{title:"Writing & Translation", subtitle:"Transcripts", category_url:"writing-translation", subcategory_url: "transcripts"},
	{title:"Writing & Translation", subtitle:"Website Content", category_url:"writing-translation", subcategory_url: "website-content"},
	{title:"Writing & Translation", subtitle:"Reviews", category_url:"writing-translation", subcategory_url: "reviews"},
	{title:"Writing & Translation", subtitle:"Resumes & Cover Letters", category_url:"writing-translation", subcategory_url: "resumes-cover-letters"},
	{title:"Writing & Translation", subtitle:"Speech Writing", category_url:"writing-translation", subcategory_url: "speech-writing"},
	{title:"Writing & Translation", subtitle:"Proofreading & Editing", category_url:"writing-translation", subcategory_url: "proofreading-editing"},
	{title:"Writing & Translation", subtitle:"Press Releases", category_url:"writing-translation", subcategory_url: "press-releases"},
	{title:"Writing & Translation", subtitle:"Other", category_url:"writing-translation", subcategory_url: "other"},

	{title:"Video & Animation", subtitle:"Commercials", category_url:"video-animation", subcategory_url: "commercials"},
	{title:"Video & Animation", subtitle:"Editing & Post Production", category_url:"video-animation", subcategory_url: "editing-post-production"},
	{title:"Video & Animation", subtitle:"Animation & 3D", category_url:"video-animation", subcategory_url: "animation-3d"},
	{title:"Video & Animation", subtitle:"Testimonials & Reviews by Actors", category_url:"video-animation", subcategory_url: "testimonials-reviews-by-actors"},
	{title:"Video & Animation", subtitle:"Puppets", category_url:"video-animation", subcategory_url: "puppets"},
	{title:"Video & Animation", subtitle:"Stop Motion", category_url:"video-animation", subcategory_url: "stop-motion"},
	{title:"Video & Animation", subtitle:"Intros", category_url:"video-animation", subcategory_url: "intros"},
	{title:"Video & Animation", subtitle:"Other", category_url:"video-animation", subcategory_url: "other"},

	{title:"Music & Audio", subtitle:"Audio Editing & Mastering", category_url:"music-audio", subcategory_url: "audio-editing-mastering"},
	{title:"Music & Audio", subtitle:"Jingles", category_url:"music-audio", subcategory_url: "jingles"},
	{title:"Music & Audio", subtitle:"Songwriting", category_url:"music-audio", subcategory_url: "songwriting"},
	{title:"Music & Audio", subtitle:"Music Lessons", category_url:"music-audio", subcategory_url: "music-lessons"},
	{title:"Music & Audio", subtitle:"Rap Music", category_url:"music-audio", subcategory_url: "rap-music"},
	{title:"Music & Audio", subtitle:"Hip-Hop Music", category_url:"music-audio", subcategory_url: "hip-hop-music"},
	{title:"Music & Audio", subtitle:"Narration & Voice-Over", category_url:"music-audio", subcategory_url: "narration-voice-over"},
	{title:"Music & Audio", subtitle:"Sound Effects & Loops", category_url:"music-audio", subcategory_url: "sound-effects-loops"},
	{title:"Music & Audio", subtitle:"Custom Ringtones", category_url:"music-audio", subcategory_url: "custom-ringtones"},
	{title:"Music & Audio", subtitle:"Voicemail Greetings", category_url:"music-audio", subcategory_url: "voicemail-greetings"},
	{title:"Music & Audio", subtitle:"Custom Songs", category_url:"music-audio", subcategory_url: "custom-songs"},
	{title:"Music & Audio", subtitle:"Other", category_url:"music-audio", subcategory_url: "other"},

	{title:"Programming & Tech", subtitle:".Net", category_url:"programming-tech", subcategory_url: "dot-net"},
	{title:"Programming & Tech", subtitle:"C++", category_url:"programming-tech", subcategory_url: "c++"},
	{title:"Programming & Tech", subtitle:"CSS & HTML", category_url:"programming-tech", subcategory_url: "css-html"},
	{title:"Programming & Tech", subtitle:"Joomla & Drupal", category_url:"programming-tech", subcategory_url: "joomle-drupal"},
	{title:"Programming & Tech", subtitle:"Databases", category_url:"programming-tech", subcategory_url: "databases"},
	{title:"Programming & Tech", subtitle:"Java", category_url:"programming-tech", subcategory_url: "java"},
	{title:"Programming & Tech", subtitle:"JavaScript", category_url:"programming-tech", subcategory_url: "javascript"},
	{title:"Programming & Tech", subtitle:"PSD to HTML", category_url:"programming-tech", subcategory_url: "psd-to-html"},
	{title:"Programming & Tech", subtitle:"WordPress", category_url:"programming-tech", subcategory_url: "wordpress"},
	{title:"Programming & Tech", subtitle:"Flash", category_url:"programming-tech", subcategory_url: "flash"},
	{title:"Programming & Tech", subtitle:"iOS, Android & Mobile", category_url:"programming-tech", subcategory_url: "ios-android-mobile"},
	{title:"Programming & Tech", subtitle:"PHP", category_url:"programming-tech", subcategory_url: "php"},
	{title:"Programming & Tech", subtitle:"QA & Software Testing", category_url:"programming-tech", subcategory_url: "qa-software-testing"},
	{title:"Programming & Tech", subtitle:"Technology", category_url:"programming-tech", subcategory_url: "technology"},
	{title:"Programming & Tech", subtitle:"Other", category_url:"programming-tech", subcategory_url: "other"},

	{title:"Gifts", subtitle:"Greeting Cards", category_url:"gifts", subcategory_url: "greeting-cards"},
	{title:"Gifts", subtitle:"Video Greetings", category_url:"gifts", subcategory_url: "voice-greetings"},
	{title:"Gifts", subtitle:"Unusual Gifts", category_url:"gifts", subcategory_url: "unusual-gifts"},
	{title:"Gifts", subtitle:"Arts & Crafts", category_url:"gifts", subcategory_url: "arts-crafts"},
	{title:"Gifts", subtitle:"Handmade Jewelry", category_url:"gifts", subcategory_url: "handsome-jewelry"},
	{title:"Gifts", subtitle:"Gifts for Geeks", category_url:"gifts", subcategory_url: "gifts-for-geeks"},
	{title:"Gifts", subtitle:"Postcards From...", category_url:"gifts", subcategory_url: "postcadrs-from"},
	{title:"Gifts", subtitle:"Recycled Crafts", category_url:"gifts", subcategory_url: "recycled-crafts"},
	{title:"Gifts", subtitle:"Other", category_url:"gifts", subcategory_url: "other"}

])